// Prototype marketplace catalog -- entirely local/static, no backend. Buying
// a listing just parses `link` through the same parseLink/addLink path a
// pasted config would go through, so the "purchased" flow is real even
// though the storefront and payment around it are mocked.

export const MOCK_LISTINGS = [
  {
    id: 'mkt-us-east-1',
    creator: 'NightRelay',
    title: 'US East — Low Latency',
    protocol: 'vless',
    region: 'United States',
    flag: '🇺🇸',
    price: 2.99,
    rating: 4.8,
    sales: 312,
    description: 'Reality-hardened VLESS node tuned for gaming and streaming. Renews monthly.',
    link: 'vless://11111111-2222-3333-4444-555555555555@us-east.example.com:443?encryption=none&security=tls&type=tcp#NightRelay-USEast',
  },
  {
    id: 'mkt-de-fra-1',
    creator: 'ObsidianVPN',
    title: 'Frankfurt — Trojan',
    protocol: 'trojan',
    region: 'Germany',
    flag: '🇩🇪',
    price: 3.49,
    rating: 4.6,
    sales: 187,
    description: 'EU-based Trojan endpoint with a 1Gbps uplink. Good for streaming and general browsing.',
    link: 'trojan://p4ssw0rd-example@fra.example.com:443?security=tls#ObsidianVPN-Frankfurt',
  },
  {
    id: 'mkt-sg-1',
    creator: 'RedLantern',
    title: 'Singapore — Shadowsocks',
    protocol: 'ss',
    region: 'Singapore',
    flag: '🇸🇬',
    price: 1.99,
    rating: 4.3,
    sales: 501,
    description: 'Budget SEA node. Popular for mobile game ping reduction.',
    link: 'ss://YWVzLTI1Ni1nY206ZXhhbXBsZS1wYXNz@sg.example.com:8388#RedLantern-Singapore',
  },
  {
    id: 'mkt-jp-1',
    creator: 'NightRelay',
    title: 'Tokyo — Hysteria2',
    protocol: 'hysteria2',
    region: 'Japan',
    flag: '🇯🇵',
    price: 4.49,
    rating: 4.9,
    sales: 94,
    description: 'QUIC-based Hysteria2 node, best pick for unstable mobile networks and high-loss links.',
    link: 'hysteria2://p4ssw0rd-example@tokyo.example.com:443?insecure=1#NightRelay-Tokyo',
  },
  {
    id: 'mkt-uk-1',
    creator: 'ObsidianVPN',
    title: 'London — VLESS Reality',
    protocol: 'vless',
    region: 'United Kingdom',
    flag: '🇬🇧',
    price: 2.49,
    rating: 4.5,
    sales: 156,
    description: 'General-purpose UK exit, reasonable for BBC iPlayer and EU-region services.',
    link: 'vless://22222222-3333-4444-5555-666666666666@lon.example.com:443?encryption=none&security=tls&type=tcp#ObsidianVPN-London',
  },
  {
    id: 'mkt-br-1',
    creator: 'RedLantern',
    title: 'São Paulo — Trojan',
    protocol: 'trojan',
    region: 'Brazil',
    flag: '🇧🇷',
    price: 1.49,
    rating: 4.1,
    sales: 63,
    description: 'South America regional node. Best latency for LATAM.',
    link: 'trojan://p4ssw0rd-example@sao.example.com:443?security=tls#RedLantern-SaoPaulo',
  },
];

export const MOCK_MY_LISTINGS = [
  {
    id: 'mine-1',
    title: 'US West — VLESS Reality',
    protocol: 'vless',
    region: 'United States',
    flag: '🇺🇸',
    price: 2.99,
    sales: 74,
    earnings: 221.26,
    status: 'live',
  },
  {
    id: 'mine-2',
    title: 'Amsterdam — Hysteria2',
    protocol: 'hysteria2',
    region: 'Netherlands',
    flag: '🇳🇱',
    price: 3.99,
    sales: 12,
    earnings: 47.88,
    status: 'live',
  },
];

export const PROTOCOL_LABELS = {
  vless: 'VLESS',
  trojan: 'Trojan',
  ss: 'Shadowsocks',
  hysteria2: 'Hysteria2',
  vmess: 'VMess',
};
